### PR TITLE
Create KMD-ETH

### PR DESCRIPTION
**Pull request by smk762**
swap KMD for ETH.

### CODE REVIEW

**Comment by cipig** [comment]
swaps have a slightly different format, it goes
1. taker fee
2. maker payment
3. taker payment
4. taker payment spent
5. maker payment spent
each one has a txid. Infos are from the swap files in mm2.

**Comment by smk762** [comment]
couldn't quite see all that with the ETH contract, will have another look.

**Comment by cipig** [comment]
look in the json-file of the swap
DB/<nodeid>/SWAPS/MY/<swapid>.json

**Comment by smk762** [comment]
Thanks, that made it easy :)

**Pull request merged**
