### PR TITLE
EGEM Integration steps

### PR DESCRIPTION
**Pull request by riddlez666**
Starting what i can to integrate EGEM with what i know and was able to find.

Any other requirements i'm glad to help fulfill to ease in the process.

### CODE REVIEW

**Comment by jl777** [comment]
"etomic": "0x0000000000000000000000000000000000000000",
without the contract number it wont work and also without proof of mm2 swaps cant allow mm2:1

**Comment by riddlez666** [comment]
By contract number you mean on ETH chain? we are not a token on ETH.

**Comment by riddlez666** [comment]
I get im missing info and understand MM2 is being worked on but also trying to help get other ETH clones/coins supported by the platform, so any info on if my efforts are in vain would be greatly helpful.

**Comment by jl777** [comment]
we will need to add a new field do denote non-ETH chains and a way to specify the servers that can be used to send transactions.

**Comment by riddlez666** [comment]
Sweet so there is a possibility with the right parts, how can i help get those parts added in.

**Comment by jl777** [comment]
presumably the ETH clone network, would clone infuria servers to provide such services

**Comment by riddlez666** [comment]
We have a Public RPC endpoint at https://lb.rpc.egem.io that handles our Metamask and CURL requests. if that's what you mean by services.

**Comment by jl777** [comment]
i dont know the details, you need to work them out with the mm2 devs

**Comment by riddlez666** [comment]
ok thank you for your time, i will reach out to them.

**Pull request closed without merging**
