### PR TITLE
Updated PGT coin electrum icon & explorer

### PR DESCRIPTION
**Pull request by pungotoken**

### CODE REVIEW

**Comment by cipig** [comment]
Hi. What about the issue that the symbol PGT is used twice in coins file?
here https://github.com/jl777/coins/blob/master/coins#L770
and here https://github.com/jl777/coins/blob/master/coins#L2850
This will cause lots of issues...

**Comment by jl777** [comment]
what is this other PGT? we should make unique coin symbols

**Comment by cipig** [comment]
The other PGT is "Puregold Token", a ERC20 token that was added as per request from "Puregold".
PGT in CMC is also "Puregold Token".

**Comment by jl777** [comment]
maybe we should rename the puregold to PUREGOLD?

**Comment by pungotoken** [comment]
wasnt aware of this one, the only possibility I see is changing coin name to something as PUNGO which I'm sure its clean for now. Getting 3 letter coins its getting harder and can easily cause collitions in the near future as hundreds of coins appear everyday

Before coin its too spread we can easily handle, as I guess PureGolden guys will not be willing to change name and its already listed in many listing sites such as coinmarketcap. Keeping same naming will only lead to confusion

so for switching to PUNGO might be a less hurting solution now than in future...

**Pull request merged**
